version: '2'

services:
  db:
    image: mysql:5.6
    volumes:
      - "./.data/db:/var/lib/mysql"
      # Place mysql dump in mysql folder for automatic import
      - "./mysql:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
  wordpress:
    depends_on:
      - db
    build:
      context: "./docker/wordpress"
    volumes:
      - "./cms:/var/www/html"
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
